# Introduction
Imagine a one-year-old child who grows up hearing both English and Spanish.
Her family has a medium-sized, four-legged creature that is furry and barks. 
She knows that this is referred to as a _dog_ <span style="font-variant:small-caps;">(eng)</span> in English.
How likely is it, then, that she knows that it is referred to as a _perro_ <span style="font-variant:small-caps;">(spa)</span> in Spanish?
What about a more difficult word---does knowing _mañana_ <span style="font-variant:small-caps;">(spa)</span> mean that she is more likely to know _tomorrow_ <span style="font-variant:small-caps;">(eng)</span>?

Studying language learning in the bilingual context is important because a large proportion of the world speaks more than one language, with estimates ranging from a third to half of the global population [see e.g., @weiDimensionsBilingualism2007; @wolckTypesNaturalBilingual1987], and the increasingly globalised world means that bi- or multilingualism is increasingly becoming the norm.
Understanding bilingual language learning is also deeply connected with a number of related issues in other fields, including pedagogy [e.g., @garciaBilingualEducation21st2011], clinical applications [e.g., @gonzalez-barreroBilingualAdjustedVocabulary2020], and language policy [e.g., @brownMaintainingHeritageLanguage2011].
In addition, because parents have some level of agency in determining the kind of bilingual environments they provide for their children [e.g., @byers-heinleinBilingualismEarlyYears2013; @dehouwerBilingualLanguageAcquisition2017], insight from bilingual language acquisition can help to inform effective, evidence-backed bilingual parenting strategies.

For the field of developmental psycholinguistics, bilingual language environments provide a natural experiment for understanding how features of the input environment can shape language outcomes. 
Comparing bilinguals and monolinguals can reveal differences in strategies or heuristics employed in word learning, thereby determining whether or not such tendencies are influenced by the type and amount of language input received. 
Indeed, there is a growing body of evidence demonstrating such differences---for example, bilingual children are sensitive to different cues during word learning [e.g., @colungaBilingualMonolingualChildren2012; @grobaBilingualMonolingualChildren2018; @luniewskaWordKnowledgeLexical2022], exhibit prolonged flexibility in interpreting word forms [e.g., @grafestesFlexibilityBilingualInfants2015], and have different expectations about metalinguistic information [e.g., @byers-heinleinSurmountingTowerBabel2014; @hendersonSheCalledThat2015], in comparison with children learning only one language. 

One unique feature of bilingual contexts is the presence of _translation equivalents_ (TEs), which are lexical items in different languages that have the same or highly similar referents (e.g., _dog_ <span style="font-variant:small-caps;">(eng)</span> and _perro_ <span style="font-variant:small-caps;">(spa)</span>).[^01-01]
Investigating TEs may shed light on the mechanisms underlying word learning, since learning environments with an increased proportion of TEs provide a word learning situation that is strikingly different from that afforded to monolingual learners, for whom synonymy is not as systematic or as widespread.
For example, the presence of TEs may be related to a reduction in bilingual learners' use of the mutual exclusivity bias---that novel words should map to novel, rather than familiar, referents---during word learning [see @lewisRoleDevelopmentalChange2020].
In the current work, we examined the role of TEs in bilingual word learning: whether knowing a word in one language increases the probability of knowing its corresponding TE. 
In other words, we investigate whether there is evidence that bilingual children use their knowledge in one language to bootstrap language learning in another.
Moreover, we explore whether this tendency varies as a function of children's age and degree of exposure to their two languages.
We also examine whether this tendency is more likely for TEs that sound more similar in the child's two languages than words that have more distinct phonological forms.
Finally, we explore how consistent the effect of TEs is across populations, and whether it varies across TEs of different lexical categories.

[^01-01]: Throughout this paper, we distinguish between _TEs_, which simply refer to translation equivalents that exist between two languages irrespective of a child's knowledge of the words in question, and _TE pairs_, which refer to pairs of TEs for which both words are known by a child.

## Studying children's vocabulary growth using parent report
Structured parent report is an especially valuable approach to investigate the broad makeup of a child's lexicon, as it allows for a global picture of the child's language.
In particular, a common tool for vocabulary measurement is the MacArthur--Bates Communicative Development Inventory [CDI; @fensonMacArthurBatesCommunicativeDevelopment2007]. 
CDIs are a family of vocabulary checklists in which parents are asked to mark words that their child "understands" or "understands and says" from a large word list, with demonstrated reliability and validity as an estimator of children's vocabularies [@fensonMacArthurBatesCommunicativeDevelopment2007; @mayorStatisticalEstimateInfant2011].
Their simplicity and cost-effectiveness, coupled with the fact that there are adaptations of CDIs in more than 100 languages, have resulted in widespread use of this tool among researchers, clinicians, and other early childhood practitioners.

The most common use-case of CDIs is to measure children's vocabulary sizes, permitting an estimation of the variation across _children_ at a given age in how many words they are reported to produce [e.g., @fensonMacArthurBatesCommunicativeDevelopment2007; @frankVariabilityConsistencyEarly2021].
The fact that CDIs contain item-level information, however, means that it is also possible to use CDI data to examine variation across _items_.
One such approach involves predicting the acquisition trajectories of individual words.
Studies of item learning in monolingual children have found that words are acquired earlier when they are more frequent in a child's language input [@goodmanDoesFrequencyCount2008], and when they are used in more distinctive contexts [@royPredictingBirthSpoken2015].
Larger-scale analyses have further been enabled by data sharing practices, via tools such as CHILDES [@macwhinneyCHILDESProjectTools2000], an open repository of child language corpora, as well as Wordbank [@frankWordbankOpenRepository2017], an open repository of CDI data.
For example, such analyses have found that there is substantial overlap in the earliest words produced by young children across different languages [@tardifBabyFirst102008], that children across most languages have a positive noun bias and a negative function word bias [@frankVariabilityConsistencyEarly2021], and that frequency and concreteness are strong positive predictors of the age of acquisition of words, whereas mean length of utterance in words is a negative predictor [@braginskyConsistencyVariabilityChildren2019].
As such, these vocabulary data allow us to capture dimensions of consistency and variability across children, across languages, and across items on the forms.

Integrating these predictive approaches with other computational models, @kachergisStandardModelEarly2022 proposed a 'standard model' of word learning based in item response theory [@embretsonItemResponseTheory2000].
This model treats word learning as an accumulation process [following @mcmurrayDefusingChildhoodVocabulary2007]: each token in a child's language input contributes information about the corresponding word, and when the child has accumulated sufficient information about a particular word (i.e., has passed a certain item-specific threshold), they are considered to know the word. 
Variability in word learning can thus be characterised by variability in language input and in word difficulty (i.e., threshold levels). 
This computational model helps to unify a number of earlier approaches, and provides an explicit formalisation of the word learning process.
In the current work, we apply this approach originally developed for the monolingual setting to bilingual children.

## Translation equivalents: Methodological challenges
The use of CDIs can be extended to bilingual children by administering two CDIs of two different languages [see @weislederUsingParentReport2022 for a scoping review].
CDIs are typically adapted and normed for monolingual populations; there are few specifically bilingual forms (but see e.g., [@deandaPsychometricPropertiesEnglish2022; @otooleParentReportEarly2017] ###Reese et al., 2017### for CDI-based forms developed for bilinguals). 
This gap means that the two-CDI approach tends to be the most accessible and most commonly used method of measuring bilingual children’s vocabularies, and has shown concurrent validity with laboratory measures in bilingual children (###Marchman & Martínez-Sussmann, 2002###).
TE knowledge can then be assessed by measuring the conceptual overlap between the two forms, by mapping items on each form onto "universal lemmas", or "unilemmas" [see @braginskyConsistencyVariabilityChildren2019]; these are approximate cross-linguistic conceptual mappings of words, verified by the judgement of native or advanced proficient speakers of the language.
For example, _dog_ <span style="font-variant:small-caps;">(eng)</span> and _perro_ <span style="font-variant:small-caps;">(spa)</span> map to the same unilemma, _<span style="font-variant:small-caps;">dog</span>_. 

This two-CDI method has supported a range of findings about TEs, including the observation that older children have a greater proportion of TE pairs in their vocabularies [e.g., @davidIndividualDifferencesLexical2008; @woodsDevelopmentTranslationEquivalents2013].
However, it is difficult to appropriately interpret this finding due to the _baseline problem_: CDIs are finite, and thus children who know a greater proportion of the words on each of the CDI forms (who tend to be older) are also directly likely to have a greater proportion of TE pairs simply by chance (i.e., as a random baseline). 
Consider an idealised scenario of word learning with two key assumptions: (1) the probability of knowing any word (on the CDI) in language $i$ is uniformly $P_i$, and (2) word knowledge in a child's two languages are independent.
In this case, the expected proportion of a bilingual child’s vocabulary composed of TE pairs is $\mathbb{E}(\textrm{\%TE}) = 2 P_1 P_2 \,/\, (P_1 + P_2)$, assuming that all items on one CDI have a corresponding TE in the CDI of the other language.[^01-02]
Then, as long as $P_1$ and $P_2$ are monotonically non-decreasing with age (which we assume to be true as long as a child is receiving input in the relevant language), $\mathbb{E}(\textrm{\%TE})$ would also be monotonically non-decreasing.[^01-03]
In other words, just knowing more words means that, by chance, a higher proportion of them happen to be translation equivalents.
Hence, simply observing an increase in proportion of TE pairs with age does not suggest that TEs play a particular role in bilingual word learning (e.g., whether children have more TE pairs compared to a meaningful baseline); instead, this observation could be merely an artifact of older children having larger vocabularies.

[^01-02]: Let $k$ be the number of items on the CDI.
Then, the expected number of TE pairs is $k P_1 P_2$, and the total vocabulary is $k P_1 + k P_2$, assuming that both CDIs have $k$ items. 
The factor of two arises from the fact that one TE pair comprises two items (one in each language).

[^01-03]: To see that $\mathbb{E}(\textrm{\%TE})$ is monotonically non-decreasing, note that the partial derivative with respect to $P_1$ is $2 P_2^2 \,/\, (P_1 + P_2)^2$, which is non-negative over the domain $[0,1]$, and similarly for $P_2$.

One way to work around the baseline problem is to compare the proportion of TE pairs known to an expected proportion of TE pairs, calculated under the null hypothesis that a bilingual child acquires their two vocabularies independently (i.e., that assumption 2 holds) [see @tsuiAreTranslationEquivalents2022].
If the independence assumption is met, then the probability of a child knowing both TEs would straightforwardly be the product of the probabilities of the child knowing each word. 
Otherwise, this equivalence would not hold---if bilingual children have a preference towards acquiring TEs, the joint probability would be greater than expected; if bilingual children instead have an avoidance against acquiring TEs, then the joint probability would be less than expected. 
Measuring the deviance from the expected values across age can thus demonstrate whether there is an interaction between TE knowledge and age---i.e., whether bias for or against TEs changes across development.

For this approach to be meaningful, one would also need to account for the fact that different words do not have the same probability of being known at any given point---in other words, different words have different ages of acquisition (i.e., assumption 1 does not hold).
To address this, @bilsonSemanticFacilitationBilingual2015 simulated word learning as the growth of a semantic network, such that words with stronger connections in the network were preferentially acquired.
They constructed a baseline by independently simulating two monolingual English lexica, then measuring the proportion of overlap between the two lexica to estimate the expected proportion of TE pairs.
They concluded that bilingual children produce a higher proportion of TE pairs than would be expected from simulated means.
However, there was considerable variability in acquisition patterns across children---out of 105 children, 24 produced significantly more TE pairs than expected, while 9 produced significantly fewer than expected. 
This variability may have been due to individual-level variables, such as age and language exposure, or variation across languages that may not have been reflected in monolingual English norms. 
These factors may have contributed additional variance that was not captured by the baseline, and deserve further investigation.

@tsuiAreTranslationEquivalents2022 opted to use a different method, by positing that the vocabulary that is potentially learnable by a child might vary with the child's developmental level.
They estimated the total learnable vocabulary size at any given age as the number representing the 90th percentile monolingual norm for the language (rather than having it constant at the full size of the corresponding CDI).
Thus, by varying the total number of words that a child _could_ know at a given age, the probability of knowing any word out of the potentially learnable vocabulary varies with age, accounting for the distribution of ages of acquisition across CDI items.
Using this model, they concluded that children with smaller vocabularies (who tend to be younger) have a preference towards acquiring TEs, whereas children with larger vocabularies (who tend to be older) are neutral towards acquiring TEs, in comparison with expected baseline values. 
However, the use of the 90th percentile as a baseline is a somewhat arbitrary decision. 
Importantly, varying the percentile used would change the outcome of the model---using a lower percentile would result in greater expected values, and vice versa. 
Therefore, finding a credible baseline is necessary to advance this line of investigation.

One additional dimension of variability to consider is the observation that TEs are not all equivalent.
Specifically, TEs vary in the degree of phonological similarity between the two items---for example, _dog_ <span style="font-variant:small-caps;">(eng)</span> and _perro_ <span style="font-variant:small-caps;">(spa)</span> have no phonological overlap, whereas _animal_ <span style="font-variant:small-caps;">(eng)</span> and _animal_ <span style="font-variant:small-caps;">(spa)</span> are very similar phonologically.
Indeed, previous research has suggested that TEs with greater phonological overlap are more likely to be TE pairs [@grassoCrossLinguisticCognateProduction2018; @umbelMeasuringBilingualChildren1992], and bilingual children produce more TE pairs that have high phonological overlap than TE pairs that have low phonological overlap [@boschFirstTranslationEquivalents2014; @mitchellCognatesAreAdvantaged2022; @umbelMeasuringBilingualChildren1992].
TEs can also vary in the lexical categories of their items: They could label, inter alia, objects, actions, or attributes, which broadly correspond to nouns, verbs, and adjectives.
These results suggest that phonological similarity and lexical category may be important factors to consider in understanding the role of TEs in bilingual word learning.

## The current work
In the present work, we adopt an alternative strategy to handle the baseline problem.
We examine the role of TEs for individual words, rather than for vocabulary size totals, estimating how the probability of knowing a word is affected by the probability of knowing its corresponding TE. 
We first model the age trajectory of each word independently, thereby, creating an unconditional prediction about the acquisition trajectory of a particular word that can be modulated by the presence or absence of a TE. 
We can then determine the extent to which the effect of knowing a TE increases or decreases depending on the age of the child. 
This item-based approach draws from previous work that estimates item acquisition trajectories for individual words---i.e., the probability that a child knows a given word at a given age [@braginskyConsistencyVariabilityChildren2019; @goodmanDoesFrequencyCount2008]. 
Thus, this method directly addresses the baseline problem (i.e., the probability that a child knows more TEs simply because they know more words) through the use of a statistical model that predicts acquisition probabilities of individual words over age rather than predicting total vocabulary size. 
A clear advantage of this approach is that it does not require the assumption that monolingual word learning norms provide a meaningful comparative reference for bilingual children [contra both @bilsonSemanticFacilitationBilingual2015; @tsuiAreTranslationEquivalents2022, see also ###Rothman et al., 2023###].
We extend this approach to additionally capture individual differences (e.g., in language exposure) as well as TE-level differences (e.g., in phonological overlap), permitting the simultaneous examination of both child-level and item-level variability, and how both contribute to bilingual word learning.

Once this model has been constructed, it is then possible to investigate variability across _groups_ of children and items---for example, examining how the role of TEs varies across different populations and language combinations, or across different item lexical categories.
Consistency across populations and language combinations would suggest that the effect of TE knowledge is robust, and that TE knowledge can serve as an equally useful source of linguistic information regardless of the specific language combinations involved. 
This would parallel findings by @braginskyConsistencyVariabilityChildren2019 that various information sources have similar relative importance across languages. 
In contrast, variability across lexical categories may suggest that TEs interact differently with the learning of different types of concepts (e.g., objects, actions, or attributes).
For example, @schelletterBilingualChildrenLexical2005 found that phonological similarity between TEs was more important for nouns than for verbs in early vocabulary. 
These results would inform us about the generalisability of the role of TEs in early bilingual word learning.

Our analytic approach involved three steps.
We first constructed a base model by adapting the standard model (which was initially developed on monolinguals) for the bilingual context, in order to determine whether known predictors of monolingual word learning also predict bilingual word learning.
We constructed our model by including input-related factors, including administration-level variables (age and language exposure) as well as a distributional property of words (frequency). 
We also included factors relating to item difficulty, including semantic and syntactic variables previously demonstrated to influence word learning (concreteness and mean length of utterance in words (MLU-w)) [see @braginskyConsistencyVariabilityChildren2019]. 
We examined the contribution of these variables, with the following hypotheses:

1. Older children have greater likelihood of word production, and greater frequency and language exposure predict greater likelihood of word production, as does the interaction between them [as predicted by the standard model; see @kachergisStandardModelEarly2022]; and
2. Higher concreteness and lower MLU-w predict greater likelihood of word production [from previous age of acquisition modelling work, e.g., @braginskyConsistencyVariabilityChildren2019].

Once this model was established, we could then approach our main goal of understanding the role of TEs.
We added TE knowledge and phonological similarity as additional predictive variables to determine if they explained some of the variance in bilingual word knowledge, with the following hypotheses:

3. Knowing a word predicts knowing its corresponding TE [due to previous results about TE knowledge, e.g., @anayaIdentifyingImpactWord2021; @grassoCrossLinguisticCognateProduction2018]; and 
4. Greater phonological similarity predicts greater likelihood of word production when the word's TE is known [based on studies suggesting that phonologically similar TEs are learnt earlier, e.g., @mitchellCognatesAreAdvantaged2022; @umbelMeasuringBilingualChildren1992].

We then conducted additional analyses to consider how these effects would hold across populations and across lexical categories, with the following hypotheses:

5. The relative importance of the various predictors is largely consistent across datasets and across language environments [given the relatively high consistencies observed by @braginskyConsistencyVariabilityChildren2019]; and
6. The importance of different predictors may vary among different lexical categories [as different sources of linguistic information may vary in importance across lexical categories, e.g., @braginskyConsistencyVariabilityChildren2019; @goodmanDoesFrequencyCount2008; @schelletterBilingualChildrenLexical2005].
