---
title: "Bilingual Word Learning - Study 2 Analyses"
author: "Alvin Tan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# data retrieval
library(wordbankr)
library(childesr)
# data handling
library(Matrix)
library(tidyverse)
library(glue)
library(broom)
library(here)
# stemming
library(hunspell)
library(SnowballC)
# plots
library(colorspace)
library(ggnewscale)
# modelling
library(brms)
library(bayestestR)

## load functions
walk(list.files("scripts", pattern = "*.R$", full.names = TRUE), source)
```

## Data loading and preparation
Load data
```{r data-load, include=FALSE}
eng_spa_mr_admins <- fetch_eng_spa_marchman_admins()
eng_spa_hf_admins <- fetch_eng_spa_hoff_admins()
eng_fra_pl_admins <- fetch_eng_fra_poulindubois_admins()
eng_fra_mt_admins <- fetch_eng_fra_mitchell_admins()
```

Get translation equivalent knowledge
```{r te}
eng_spa_mr_admins <- add_trans_equiv(eng_spa_mr_admins)
eng_spa_hf_admins <- add_trans_equiv(eng_spa_hf_admins)
eng_fra_pl_admins <- add_trans_equiv(eng_fra_pl_admins)
eng_fra_mt_admins <- add_trans_equiv(eng_fra_mt_admins)
```

Get phonological similarity
```{r phon-sim, include=FALSE}
eng_spa_phon_sim <- get_phon_sim("English (American)", "Spanish (Mexican)")
eng_fra_phon_sim <- get_phon_sim("English (American)", "French (Quebecois)")
```

Get psychological predictors
```{r preds, include=FALSE}
concreteness_map <- c(word = "Word", concreteness = "Conc.M")
concreteness_eng_spa <- eng_spa_mr_admins |> map_predictor("concreteness", concreteness_map)
concreteness_eng_fra <- eng_fra_pl_admins |> map_predictor("concreteness", concreteness_map)
```

Get CHILDES metrics
```{r childes}
eng_uni_lemmas <- get_uni_lemmas("English (American)")
spa_uni_lemmas <- get_uni_lemmas("Spanish (Mexican)")
fra_uni_lemmas <- get_uni_lemmas("French (Quebecois)")

uni_lemmas <- bind_rows(eng_uni_lemmas, spa_uni_lemmas, fra_uni_lemmas) |> 
  unique() |> 
  na.omit()

childes_metrics <- load_childes_metrics(languages = c("English (American)",
                                                     "Spanish (Mexican)",
                                                     "French (Quebecois)"),
                                        uni_lemmas = uni_lemmas) |> 
  transform_counts()
```

Join all predictors and transform (centre and scale)
```{r join}
mr_data <- join_and_transform(eng_spa_mr_admins, childes_metrics,
                              concreteness_eng_spa, eng_spa_phon_sim)
hf_data <- join_and_transform(eng_spa_hf_admins, childes_metrics,
                              concreteness_eng_spa, eng_spa_phon_sim)
pl_data <- join_and_transform(eng_fra_pl_admins, childes_metrics,
                              concreteness_eng_fra, eng_fra_phon_sim)
mt_data <- join_and_transform(eng_fra_mt_admins, childes_metrics,
                              concreteness_eng_fra, eng_fra_phon_sim)
```

Select complete cases
```{r complete}
mr_complete <- select_complete(mr_data)
hf_complete <- select_complete(hf_data)
pl_complete <- select_complete(pl_data)
mt_complete <- select_complete(mt_data)

saveRDS(mr_complete, "outputs/mr_complete.rds")
```

## Modelling
Model using brms
```{r model-mr}
mr_model_base <- run_model(mr_complete, base_formula)
mr_model_te <- run_model(mr_complete, te_formula)
mr_model_full <- run_model(mr_complete, full_formula)
```

```{r model-hf}
hf_model_base <- run_model(hf_complete, base_formula)
hf_model_te <- run_model(hf_complete, te_formula)
hf_model_full <- run_model(hf_complete, full_formula)
```

```{r model-pd}
pl_model_base <- run_model(pl_complete, base_formula)
pl_model_te <- run_model(pl_complete, te_formula)
pl_model_full <- run_model(pl_complete, full_formula)
```

```{r model-mt}
mt_model_base <- run_model(mt_complete, base_formula)
mt_model_te <- run_model(mt_complete, te_formula)
mt_model_full <- run_model(mt_complete, full_formula)
```

```{r model-mr-pred}
mr_pred <- predict(mr_model_base, re_formula = NA)
mr_complete_pred <- mr_complete |>
  cbind(mr_pred) |>
  mutate(freq_t_binned = cut(freq_t, c(-Inf,-0.5,0,0.5,Inf)),
         lang_prop_binned = cut(lang_prop, c(0, 40, 60, 100), 
                                include.lowest = TRUE))
saveRDS(mr_complete_pred, "outputs/mr_complete_pred.rds")
```

Extract coefficients
```{r coefs-base}
mr_mp_b <- get_model_posteriors(mr_model_base, "Eng-Spa (Marchman)")
hf_mp_b <- get_model_posteriors(hf_model_base, "Eng-Spa (Hoff)")
pl_mp_b <- get_model_posteriors(pl_model_base, "Eng-Fra (Poulin-Dubois)")
mt_mp_b <- get_model_posteriors(mt_model_base, "Eng-Fra (Mitchell)")

mp_b <- rbind(mr_mp_b, hf_mp_b, pl_mp_b, mt_mp_b)
saveRDS(mp_b, "outputs/mp_b.rds")
mp_b_plot <- plot_coefs(mp_b)
```

```{r coefs-te}
mr_mp_t <- get_model_posteriors(mr_model_te, "Eng-Spa (Marchman)")
hf_mp_t <- get_model_posteriors(hf_model_te, "Eng-Spa (Hoff)")
pl_mp_t <- get_model_posteriors(pl_model_te, "Eng-Fra (Poulin-Dubois)")
mt_mp_t <- get_model_posteriors(mt_model_te, "Eng-Fra (Mitchell)")

mp_t <- rbind(mr_mp_t, hf_mp_t, pl_mp_t, mt_mp_t)
saveRDS(mp_t, "outputs/mp_t.rds")
mp_t_plot <- plot_coefs(mp_t)
```

```{r coefs-full}
mr_mp_f <- get_model_posteriors(mr_model_full, "Eng-Spa (Marchman)")
hf_mp_f <- get_model_posteriors(hf_model_full, "Eng-Spa (Hoff)")
pl_mp_f <- get_model_posteriors(pl_model_full, "Eng-Fra (Poulin-Dubois)")
mt_mp_f <- get_model_posteriors(mt_model_full, "Eng-Fra (Mitchell)")

mp_f <- rbind(mr_mp_f, hf_mp_f, pl_mp_f, mt_mp_f)
saveRDS(mp_f, "outputs/mp_f.rds")
mp_f_plot <- plot_coefs(mp_f)
```

Lexical class analysis
```{r lc-full}
mr_lc_models_full <- run_lc_models(mr_complete, full_formula)
hf_lc_models_full <- run_lc_models(hf_complete, full_formula)
pl_lc_models_full <- run_lc_models(pl_complete, full_formula)
mt_lc_models_full <- run_lc_models(mt_complete, full_formula)
```

```{r lc-coefs}
mr_mp_lc_full <- get_lc_models_posteriors(mr_lc_models_full, "Eng-Spa (Marchman)")
hf_mp_lc_full <- get_lc_models_posteriors(hf_lc_models_full, "Eng-Spa (Hoff)")
pl_mp_lc_full <- get_lc_models_posteriors(pl_lc_models_full, "Eng-Fra (Poulin-Dubois)")
mt_mp_lc_full <- get_lc_models_posteriors(mt_lc_models_full, "Eng-Fra (Mitchell)")

mp_lc_f <- rbind(mr_mp_lc_full, hf_mp_lc_full, pl_mp_lc_full, mt_mp_lc_full)
saveRDS(mp_lc_f, "outputs/mp_lc_f.rds")
```

